/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ps.client.form;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.client.controller.ClientController;
import rs.ac.bg.fon.ps.client.model.StavkaUslugeTableModel;
import rs.ac.bg.fon.ps.common.domain.GenericEntity;
import rs.ac.bg.fon.ps.common.domain.Klijent;
import rs.ac.bg.fon.ps.common.domain.Materijal;
import rs.ac.bg.fon.ps.common.domain.StavkaUsluge;
import rs.ac.bg.fon.ps.common.domain.Usluga;
import rs.ac.bg.fon.ps.common.domain.Zubar;

/**
 *
 * @author ognje
 */
public class FrmUsluga extends javax.swing.JFrame {

    private FrmPregledUsluga parentForma;
    private StavkaUslugeTableModel sutm;
    
    private Usluga uslugaZaIzmenu;
   
    
    /**
     * Creates new form FrmUsluga
     */
    public FrmUsluga() {
        sutm = new StavkaUslugeTableModel();
        initComponents();
        ucitajZubare();
        ucitajKlijente();
        ucitajMaterijale();
    }
    
    public FrmUsluga(FrmPregledUsluga parentForma, Usluga usluga){
        this();
        this.parentForma = parentForma;
        this.uslugaZaIzmenu = usluga;
        popuniFormu(usluga);
        btnSacuvaj.setText("Izmeni uslugu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbZubar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbKlijent = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbMaterijal = new javax.swing.JComboBox<>();
        txtKolicina = new javax.swing.JTextField();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();
        btnIzracunaj = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUkupanSaPopustom = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv usluge:");

        jLabel2.setText("Zubar:");

        jLabel3.setText("Klijent:");

        jLabel4.setText("Materijal:");

        jLabel5.setText("Kolicina:");

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        tblStavke.setModel(sutm);
        jScrollPane1.setViewportView(tblStavke);

        jLabel6.setText("Popust:");

        txtPopust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPopustActionPerformed(evt);
            }
        });

        btnIzracunaj.setText("Izracunaj");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });

        jLabel7.setText("Ukupan iznos:");

        txtUkupanIznos.setEditable(false);

        jLabel8.setText("Ukupno sa popustom:");

        txtUkupanSaPopustom.setEditable(false);

        btnSacuvaj.setText("Sacuvaj uslugu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNaziv)
                                    .addComponent(cmbZubar, 0, 163, Short.MAX_VALUE)
                                    .addComponent(cmbKlijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbMaterijal, 0, 189, Short.MAX_VALUE)
                                            .addComponent(txtKolicina)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUkupanSaPopustom, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnIzracunaj, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(cmbMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbZubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnObrisiStavku))
                    .addComponent(btnDodajStavku))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtUkupanSaPopustom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzracunaj)
                    .addComponent(btnSacuvaj))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPopustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPopustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPopustActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        dodajStavku();
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        obrisiStavku();
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed
        izracunaj();
    }//GEN-LAST:event_btnIzracunajActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        sacuvajIliIzmeniUslugu();
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsluga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsluga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsluga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsluga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsluga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Klijent> cmbKlijent;
    private javax.swing.JComboBox<Materijal> cmbMaterijal;
    private javax.swing.JComboBox<Zubar> cmbZubar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtUkupanIznos;
    private javax.swing.JTextField txtUkupanSaPopustom;
    // End of variables declaration//GEN-END:variables

    private void ucitajZubare() {
        try {
            List<GenericEntity> lista = ClientController.getInstance().getAllZubar();
            cmbZubar.removeAllItems();
            for (GenericEntity ge : lista) {
                cmbZubar.addItem((Zubar) ge);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju zubara: " + e.getMessage());
        }
    }

    private void ucitajKlijente() {
        try {
            List<GenericEntity> lista = ClientController.getInstance().getAllKlijent();
            cmbKlijent.removeAllItems();
            for (GenericEntity ge : lista) {
                cmbKlijent.addItem((Klijent) ge);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju klijenata: " + e.getMessage());
        }
    }

    private void ucitajMaterijale() {
        try {
            List<GenericEntity> lista = ClientController.getInstance().getAllMaterijal();
            cmbMaterijal.removeAllItems();
            for (GenericEntity ge : lista) {
                cmbMaterijal.addItem((Materijal) ge);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju materijala: " + e.getMessage());
        }
    }

    private void dodajStavku() {
        try {
            Materijal materijal = (Materijal) cmbMaterijal.getSelectedItem();

            if (materijal == null) {
                JOptionPane.showMessageDialog(this, "Izaberite materijal.");
                return;
            }

            int kolicina = Integer.parseInt(txtKolicina.getText().trim());

            if (kolicina <= 0) {
                JOptionPane.showMessageDialog(this, "Kolicina mora biti veca od 0.");
                return;
            }

            StavkaUsluge stavka = new StavkaUsluge();
            stavka.setMaterijal(materijal);
            stavka.setKolicina(kolicina);
            stavka.setCena(materijal.getCena());
            stavka.setIznos(kolicina * materijal.getCena());

            sutm.addStavka(stavka);
            txtKolicina.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kolicina mora biti broj.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void obrisiStavku() {
        int row = tblStavke.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite stavku.");
            return;
        }

        sutm.removeStavka(row);
    }

    private void izracunaj() {
        try {
            double ukupan = 0;

            for (StavkaUsluge s : sutm.getLista()) {
                ukupan += s.getIznos();
            }

            double popust = 0;
            if (!txtPopust.getText().trim().isEmpty()) {
                popust = Double.parseDouble(txtPopust.getText().trim());
            }

            double saPopustom = ukupan - (ukupan * popust / 100.0);

            txtUkupanIznos.setText(String.valueOf(ukupan));
            txtUkupanSaPopustom.setText(String.valueOf(saPopustom));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Popust mora biti broj.");
        }
    }

    private void sacuvajIliIzmeniUslugu() {
        try {
            String naziv = txtNaziv.getText().trim();
            Zubar zubar = (Zubar) cmbZubar.getSelectedItem();
            Klijent klijent = (Klijent) cmbKlijent.getSelectedItem();

            if (naziv.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Unesite naziv usluge.");
                return;
            }

            if (zubar == null) {
                JOptionPane.showMessageDialog(this, "Izaberite zubara.");
                return;
            }

            if (klijent == null) {
                JOptionPane.showMessageDialog(this, "Izaberite klijenta.");
                return;
            }

            if (sutm.getLista().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Dodajte bar jednu stavku.");
                return;
            }

            if (txtUkupanIznos.getText().trim().isEmpty() || txtUkupanSaPopustom.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Prvo kliknite na Izracunaj.");
                return;
            }

            Usluga u = new Usluga();
            if (uslugaZaIzmenu != null) {
                u.setUslugaId(uslugaZaIzmenu.getUslugaId());
            }

            u.setNaziv(naziv);
            u.setZubar(zubar);
            u.setKlijent(klijent);
            u.setStavke(new ArrayList<>(sutm.getLista()));
            u.setUkupanIznos(Double.parseDouble(txtUkupanIznos.getText().trim()));

            double popust = 0;
            if (!txtPopust.getText().trim().isEmpty()) {
                popust = Double.parseDouble(txtPopust.getText().trim());
            }

            u.setPopust(popust);
            u.setUkupanIznosSaPopustom(Double.parseDouble(txtUkupanSaPopustom.getText().trim()));

            if (uslugaZaIzmenu == null) {
                ClientController.getInstance().addUsluga(u);
                JOptionPane.showMessageDialog(this, "Usluga uspesno sacuvana.");
            } else {
                ClientController.getInstance().updateUsluga(u);
                JOptionPane.showMessageDialog(this, "Usluga uspesno izmenjena.");
                
                if(parentForma != null){
                    parentForma.osveziTabeluUsluga();
                }
            }
            
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void popuniFormu(Usluga u) {
        try {
            txtNaziv.setText(u.getNaziv());
            txtPopust.setText(String.valueOf(u.getPopust()));
            txtUkupanIznos.setText(String.valueOf(u.getUkupanIznos()));
            txtUkupanSaPopustom.setText(String.valueOf(u.getUkupanIznosSaPopustom()));

            cmbZubar.setSelectedItem(u.getZubar());
            cmbKlijent.setSelectedItem(u.getKlijent());

            List<GenericEntity> lista = ClientController.getInstance().getStavkeByUsluga(u);
            List<StavkaUsluge> stavke = new ArrayList<>();

            for (GenericEntity ge : lista) {
                stavke.add((StavkaUsluge) ge);
            }

            sutm.setLista(stavke);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri popunjavanju forme: " + e.getMessage());
        }
    }
}
